In [7]:
import numpy as np
import pandas as pd

X = np.array([[1.0, 2.0, 3.0],   # (2 samples, 3 features)
              [4.0, 5.0, 6.0]])

means = np.array([[2.0, 3.0, 4.0], # (2 classes, 3 features)
                  [5.0, 6.0, 7.0]])

X_expanded1 = X[:, np.newaxis, :]
X_expanded2 = X[np.newaxis, :, :]
X_expanded3 = X[:, :, np.newaxis]

print(X_expanded1)
print("1 \n")
print(X_expanded2)
print("2 \n")
print(X_expanded3)

# Subtracting means
diff1 = X_expanded1 - means
diff2 = X_expanded2 - means
#diff3 = X_expanded3 - means

print("3 \n")
print(diff1)
print("\n")
print(diff2)
#print(diff3)



[[[1. 2. 3.]]

 [[4. 5. 6.]]]
1 

[[[1. 2. 3.]
  [4. 5. 6.]]]
2 

[[[1.]
  [2.]
  [3.]]

 [[4.]
  [5.]
  [6.]]]
3 

[[[-1. -1. -1.]
  [-4. -4. -4.]]

 [[ 2.  2.  2.]
  [-1. -1. -1.]]]


[[[-1. -1. -1.]
  [-1. -1. -1.]]]
